name: Danger

on:
  pull_request:
    branches:
      - '**'
  issue_comment:
    types:
      - created

jobs:
  danger-for-internal:
    name: Danger for internal - node.js 12.x
    if: |
      github.event_name == 'pull_request'
      && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
    - name: Clone the source for the event
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Danger JS
      run: npx danger ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  danger-for-external:
    name: Danger for external - node.js 12.x
    if: |
      github.event_name == 'issue_comment' && github.event.action == 'created'
      && github.event.issue.pull_request != null 
      && startsWith(github.event.comment.body, '/danger')
#      && github.event.pull_request.head.repo.full_name == !github.repository
    runs-on: ubuntu-latest
    steps:
    - name: Clone the action source
      uses: actions/checkout@v2
    - name: Check repository permission for user
      id: permission
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        required-permission: write
        reaction-permitted: rocket
        comment-not-permitted: Sorry, you don't have enough permission to execute `/danger`...
    - name: Clone the PR source
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{ github.event.issue.number }}/head
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Danger JS
      run: npx danger ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
